---
events:
  2021:
    label: "Experiencecon"
    dates:
      - ticket-name-contains: "*"
        date: "March 11, 2021"
   
    catering:
      - ticket-name-contains: "*"
        net-price: 0
    invoice:
      id-prefix: "TLNTB"
      logo-image: ""
      comment: |
       
        Paid in full.
      e-invoice: false
      currency: EUR
    email:
      reply-to-address: "judit.rt@talentbrand.io"
      subject: "Your invoice for ExperienceCon2021"
      message: |
        Dear Attendee!

        Thank you for taking part in ExperienceCon2021

        Please find attached our official invoice for the ExperienceCon2021.
        In case you have an issue with the invoice please reply to this e-mail.
        In case you have a general question regarding the conference please write to: judit.rt@talentbrand.io

        The ExperienceCon Team 

    bank:
      name: "Erste Bank, SWIFT: GIBAHUHB"
      account-number: "HU27116000060000000084273237"
    tito-signature-validator-env: TITO_TOKEN_EXPERIENCECON2021
